# Generated by Django 3.0.8 on 2020-08-12 14:17

from django.db import migrations, models
import django.db.models.deletion
import django_model_to_dict.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(max_length=200)),
                ('data_entrega', models.DateField()),
                ('quantidade', models.IntegerField()),
                ('estado', models.CharField(choices=[('Aceite', 'Aceite'), ('Rejeitada', 'Rejeitada'), ('Ongoing', 'Ongoing')], max_length=20)),
                ('ordem_fabrico', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cliente')),
            ],
            bases=(django_model_to_dict.mixins.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='Tipo')),
                ('start', models.DateField(verbose_name='Data inicio')),
                ('end', models.DateField(verbose_name='Data Fim')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progresso')),
                ('quantidade', models.IntegerField()),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Planeada', 'Planeada')], max_length=20)),
                ('subcontrato', models.CharField(blank=True, max_length=20, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.fornecedor', to_field='nome_fornecedor')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.Project', verbose_name='Encomenda')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django_model_to_dict.mixins.ToDictMixin),
        ),
    ]
